---
title: "When Do Regulators Lean Against the Wind?: The Political Economy of Implementing Macro-prudential Regulatory Tools: Some very preliminary results"
author: "Jeffrey Chwieroth and Christopher Gandrud"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
bibliography: main.bib
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(texreg)

# Run regressions
source('analysis/regressions_v2.R')
```

This document contains **preliminary** results. Comments welcome.[^authors]

\begin{abstract}
In the aftermath of the global financial crisis, macro-prudential regulatory (MPR) tools, which aim to limit the build-up of systemic risk and the macroeconomic costs of financial instability, have gained widespread attention. An important element of MPR tools involves implementing new counter-cyclical regulatory measures to dampen credit cycles. Yet the political dynamics of MPR tools are complicated in that their implementation involves moving against market and public sentiment during boom periods as well as affecting who can obtain access to financing and who cannot. In this sense, the use of MPR tools can be highly and conspicuously distributional, thus potentially constraining their use and effectiveness. In many cases, the allocation of MPR responsibilities to hitherto independent central banks creates additional concerns about the nature of their accountability relationship with the rest of the political process and the public at large. To shed light on these critical issues, we provide the first cross-national statistical political economy analysis of MPR implementation. Our analysis assesses the relative importance of political credit cycles, institutional demands, and societal demands for credit tightening and easing. \textbf{Preliminary results} from democracies indicate that independent central banks are important for overcoming the political credit cycles that would hamper effective MPR tightening. Conversely, [GET]
\end{abstract}

# Dependent variables

Our two dependent variables are derived from a new data set of macro-prudential regulatory (MPR) actions created by @dReinhardt2015. Aggregating a number of sources, mostly from IMF staff economists, and supplemented with additional hand-coded incidents, they generated binary quarterly indicators of MPR tightening and loosening for 70 countries between 1990 and 2014. They created dummies for a range of individual MPR instruments including lending standards, reserve requirements, capital regulation, risk weights, underwriting standards, profit distribution, and loan to value ratios.

Given that in the sample the use of some of these policies is rarely observed, we created two summary dummy variables from the @dReinhardt2015 data to use as our dependent variables. One variable captured if a country took an action that @dReinhardt2015 classified as MPR tightening in a given quarter. The other dependent variable captures loosening. These variables equal one for each country-year that any macro-prudential policy was tightened or loosened, respectively, and zero otherwise.

# Right-hand variables

We examined how a number of political and economic factors may affect decisions to tighten and loosen macro-prudential policy.

[FILL IN]



# Preliminary results

Because we are primarily interested in how politicians with electoral incentives choose macro-prudential policies, in the following regressions we focus on county-years with a Polity 2 score greater than five [@Marshall2009 updated through 2012]. This is the threshold at which the index's authors decide whether a country is democratic or not.

The following tables are from logistic regressions with country and quarter fixed effects.[^qt_fe] To avoid problem well known problems of unrealistic logistic regression coefficient sizes and, in the extreme case, complete separation we include minimal prior information suggested by @Gelman2008.[^bayesglm] Additionally, we may expect that countries that a country that has already tightened has a higher propensity to tighten again and having previously tightened is necessary to be able to loosen. As such we include a variable of **cumulative observed macroprudential policy tightening**. This variable simply sums the number of observed instances of tightening by a country up to, but not including the present quarter. Results were largely substantively the same regardless of whether or not we include this variable.[^cum_include]







# References

[^authors]: Jeffrey Chweiroth is a Professor of International Political Economy at the London School of Economics (j.m.chwieroth@lse.ac.uk). Christopher Gandrud is a Lecturer of Quantitative International Political Economy at City University London and Post-doctoral Fellow at the Hertie School of Governance (christopher.gandrud@city.ac.uk).

[^hyde4]: We used Version 4 of the data set.

[^wdi]: The indicator IDs are FP.CPI.TOTL.ZG, NY.GDP.MKTP.KD.ZG, FS.AST.DOMS.GD.ZS, respectively. Note that we created the domestic credit growth variable by finding the year-on-year percentage change in domestic credit as a percentage of GDP.

[^cum_include]: Only results from regressions including the variable are show.

[^qt_fe]: We consistently found that policies (both tightening and loosening) were more likely to be recorded by @dReinhardt2015 as occurring in the first quarter of the year.

[^bayesglm]: We implemented this with the `bayesglm` function from the **arm** package [@armR] in R [@citeR].

[^elections_skept]: We are cautious about this finding at this point as it is somewhat model dependent (i.e. there is no statistically significant effect of elections in a model without other covariates).
